//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussion_Enligne.srv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="returnList", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class returnList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Discussion_Enligne.srv.ArrayOfString emipseudosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Discussion_Enligne.srv.ArrayOfString textsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Discussion_Enligne.srv.ArrayOfInt idsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Discussion_Enligne.srv.ArrayOfString emipseudos {
            get {
                return this.emipseudosField;
            }
            set {
                if ((object.ReferenceEquals(this.emipseudosField, value) != true)) {
                    this.emipseudosField = value;
                    this.RaisePropertyChanged("emipseudos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Discussion_Enligne.srv.ArrayOfString texts {
            get {
                return this.textsField;
            }
            set {
                if ((object.ReferenceEquals(this.textsField, value) != true)) {
                    this.textsField = value;
                    this.RaisePropertyChanged("texts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Discussion_Enligne.srv.ArrayOfInt ids {
            get {
                return this.idsField;
            }
            set {
                if ((object.ReferenceEquals(this.idsField, value) != true)) {
                    this.idsField = value;
                    this.RaisePropertyChanged("ids");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srv.ws_chatSoap")]
    public interface ws_chatSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudo de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Participer", ReplyAction="*")]
        Discussion_Enligne.srv.ParticiperResponse Participer(Discussion_Enligne.srv.ParticiperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Participer", ReplyAction="*")]
        System.IAsyncResult BeginParticiper(Discussion_Enligne.srv.ParticiperRequest request, System.AsyncCallback callback, object asyncState);
        
        Discussion_Enligne.srv.ParticiperResponse EndParticiper(System.IAsyncResult result);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudo_em de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addMessage", ReplyAction="*")]
        Discussion_Enligne.srv.addMessageResponse addMessage(Discussion_Enligne.srv.addMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/addMessage", ReplyAction="*")]
        System.IAsyncResult BeginaddMessage(Discussion_Enligne.srv.addMessageRequest request, System.AsyncCallback callback, object asyncState);
        
        Discussion_Enligne.srv.addMessageResponse EndaddMessage(System.IAsyncResult result);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudo_recep de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessage", ReplyAction="*")]
        Discussion_Enligne.srv.getMessageResponse getMessage(Discussion_Enligne.srv.getMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getMessage", ReplyAction="*")]
        System.IAsyncResult BegingetMessage(Discussion_Enligne.srv.getMessageRequest request, System.AsyncCallback callback, object asyncState);
        
        Discussion_Enligne.srv.getMessageResponse EndgetMessage(System.IAsyncResult result);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudo de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        Discussion_Enligne.srv.DeleteResponse Delete(Discussion_Enligne.srv.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.IAsyncResult BeginDelete(Discussion_Enligne.srv.DeleteRequest request, System.AsyncCallback callback, object asyncState);
        
        Discussion_Enligne.srv.DeleteResponse EndDelete(System.IAsyncResult result);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetParticipantsResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParticipants", ReplyAction="*")]
        Discussion_Enligne.srv.GetParticipantsResponse GetParticipants(Discussion_Enligne.srv.GetParticipantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetParticipants", ReplyAction="*")]
        System.IAsyncResult BeginGetParticipants(Discussion_Enligne.srv.GetParticipantsRequest request, System.AsyncCallback callback, object asyncState);
        
        Discussion_Enligne.srv.GetParticipantsResponse EndGetParticipants(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticiperRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Participer", Namespace="http://tempuri.org/", Order=0)]
        public Discussion_Enligne.srv.ParticiperRequestBody Body;
        
        public ParticiperRequest() {
        }
        
        public ParticiperRequest(Discussion_Enligne.srv.ParticiperRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticiperRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo;
        
        public ParticiperRequestBody() {
        }
        
        public ParticiperRequestBody(string pseudo) {
            this.pseudo = pseudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticiperResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParticiperResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion_Enligne.srv.ParticiperResponseBody Body;
        
        public ParticiperResponse() {
        }
        
        public ParticiperResponse(Discussion_Enligne.srv.ParticiperResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticiperResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Discussion_Enligne.srv.ArrayOfString ParticiperResult;
        
        public ParticiperResponseBody() {
        }
        
        public ParticiperResponseBody(Discussion_Enligne.srv.ArrayOfString ParticiperResult) {
            this.ParticiperResult = ParticiperResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addMessage", Namespace="http://tempuri.org/", Order=0)]
        public Discussion_Enligne.srv.addMessageRequestBody Body;
        
        public addMessageRequest() {
        }
        
        public addMessageRequest(Discussion_Enligne.srv.addMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo_em;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pseudo_recep;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string text;
        
        public addMessageRequestBody() {
        }
        
        public addMessageRequestBody(string pseudo_em, string pseudo_recep, string text) {
            this.pseudo_em = pseudo_em;
            this.pseudo_recep = pseudo_recep;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion_Enligne.srv.addMessageResponseBody Body;
        
        public addMessageResponse() {
        }
        
        public addMessageResponse(Discussion_Enligne.srv.addMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addMessageResponseBody {
        
        public addMessageResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessage", Namespace="http://tempuri.org/", Order=0)]
        public Discussion_Enligne.srv.getMessageRequestBody Body;
        
        public getMessageRequest() {
        }
        
        public getMessageRequest(Discussion_Enligne.srv.getMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo_recep;
        
        public getMessageRequestBody() {
        }
        
        public getMessageRequestBody(string pseudo_recep) {
            this.pseudo_recep = pseudo_recep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion_Enligne.srv.getMessageResponseBody Body;
        
        public getMessageResponse() {
        }
        
        public getMessageResponse(Discussion_Enligne.srv.getMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Discussion_Enligne.srv.returnList getMessageResult;
        
        public getMessageResponseBody() {
        }
        
        public getMessageResponseBody(Discussion_Enligne.srv.returnList getMessageResult) {
            this.getMessageResult = getMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public Discussion_Enligne.srv.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(Discussion_Enligne.srv.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string pseudo) {
            this.pseudo = pseudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion_Enligne.srv.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(Discussion_Enligne.srv.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteResponseBody {
        
        public DeleteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParticipantsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParticipants", Namespace="http://tempuri.org/", Order=0)]
        public Discussion_Enligne.srv.GetParticipantsRequestBody Body;
        
        public GetParticipantsRequest() {
        }
        
        public GetParticipantsRequest(Discussion_Enligne.srv.GetParticipantsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetParticipantsRequestBody {
        
        public GetParticipantsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParticipantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParticipantsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion_Enligne.srv.GetParticipantsResponseBody Body;
        
        public GetParticipantsResponse() {
        }
        
        public GetParticipantsResponse(Discussion_Enligne.srv.GetParticipantsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParticipantsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Discussion_Enligne.srv.ArrayOfString GetParticipantsResult;
        
        public GetParticipantsResponseBody() {
        }
        
        public GetParticipantsResponseBody(Discussion_Enligne.srv.ArrayOfString GetParticipantsResult) {
            this.GetParticipantsResult = GetParticipantsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ws_chatSoapChannel : Discussion_Enligne.srv.ws_chatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParticiperCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ParticiperCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Discussion_Enligne.srv.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Discussion_Enligne.srv.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Discussion_Enligne.srv.returnList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Discussion_Enligne.srv.returnList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetParticipantsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetParticipantsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Discussion_Enligne.srv.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Discussion_Enligne.srv.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ws_chatSoapClient : System.ServiceModel.ClientBase<Discussion_Enligne.srv.ws_chatSoap>, Discussion_Enligne.srv.ws_chatSoap {
        
        private BeginOperationDelegate onBeginParticiperDelegate;
        
        private EndOperationDelegate onEndParticiperDelegate;
        
        private System.Threading.SendOrPostCallback onParticiperCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddMessageDelegate;
        
        private EndOperationDelegate onEndaddMessageDelegate;
        
        private System.Threading.SendOrPostCallback onaddMessageCompletedDelegate;
        
        private BeginOperationDelegate onBegingetMessageDelegate;
        
        private EndOperationDelegate onEndgetMessageDelegate;
        
        private System.Threading.SendOrPostCallback ongetMessageCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetParticipantsDelegate;
        
        private EndOperationDelegate onEndGetParticipantsDelegate;
        
        private System.Threading.SendOrPostCallback onGetParticipantsCompletedDelegate;
        
        public ws_chatSoapClient() {
        }
        
        public ws_chatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ws_chatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_chatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_chatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ParticiperCompletedEventArgs> ParticiperCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> addMessageCompleted;
        
        public event System.EventHandler<getMessageCompletedEventArgs> getMessageCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteCompleted;
        
        public event System.EventHandler<GetParticipantsCompletedEventArgs> GetParticipantsCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion_Enligne.srv.ParticiperResponse Discussion_Enligne.srv.ws_chatSoap.Participer(Discussion_Enligne.srv.ParticiperRequest request) {
            return base.Channel.Participer(request);
        }
        
        public Discussion_Enligne.srv.ArrayOfString Participer(string pseudo) {
            Discussion_Enligne.srv.ParticiperRequest inValue = new Discussion_Enligne.srv.ParticiperRequest();
            inValue.Body = new Discussion_Enligne.srv.ParticiperRequestBody();
            inValue.Body.pseudo = pseudo;
            Discussion_Enligne.srv.ParticiperResponse retVal = ((Discussion_Enligne.srv.ws_chatSoap)(this)).Participer(inValue);
            return retVal.Body.ParticiperResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Discussion_Enligne.srv.ws_chatSoap.BeginParticiper(Discussion_Enligne.srv.ParticiperRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginParticiper(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginParticiper(string pseudo, System.AsyncCallback callback, object asyncState) {
            Discussion_Enligne.srv.ParticiperRequest inValue = new Discussion_Enligne.srv.ParticiperRequest();
            inValue.Body = new Discussion_Enligne.srv.ParticiperRequestBody();
            inValue.Body.pseudo = pseudo;
            return ((Discussion_Enligne.srv.ws_chatSoap)(this)).BeginParticiper(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion_Enligne.srv.ParticiperResponse Discussion_Enligne.srv.ws_chatSoap.EndParticiper(System.IAsyncResult result) {
            return base.Channel.EndParticiper(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Discussion_Enligne.srv.ArrayOfString EndParticiper(System.IAsyncResult result) {
            Discussion_Enligne.srv.ParticiperResponse retVal = ((Discussion_Enligne.srv.ws_chatSoap)(this)).EndParticiper(result);
            return retVal.Body.ParticiperResult;
        }
        
        private System.IAsyncResult OnBeginParticiper(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pseudo = ((string)(inValues[0]));
            return this.BeginParticiper(pseudo, callback, asyncState);
        }
        
        private object[] OnEndParticiper(System.IAsyncResult result) {
            Discussion_Enligne.srv.ArrayOfString retVal = this.EndParticiper(result);
            return new object[] {
                    retVal};
        }
        
        private void OnParticiperCompleted(object state) {
            if ((this.ParticiperCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ParticiperCompleted(this, new ParticiperCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ParticiperAsync(string pseudo) {
            this.ParticiperAsync(pseudo, null);
        }
        
        public void ParticiperAsync(string pseudo, object userState) {
            if ((this.onBeginParticiperDelegate == null)) {
                this.onBeginParticiperDelegate = new BeginOperationDelegate(this.OnBeginParticiper);
            }
            if ((this.onEndParticiperDelegate == null)) {
                this.onEndParticiperDelegate = new EndOperationDelegate(this.OnEndParticiper);
            }
            if ((this.onParticiperCompletedDelegate == null)) {
                this.onParticiperCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnParticiperCompleted);
            }
            base.InvokeAsync(this.onBeginParticiperDelegate, new object[] {
                        pseudo}, this.onEndParticiperDelegate, this.onParticiperCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion_Enligne.srv.addMessageResponse Discussion_Enligne.srv.ws_chatSoap.addMessage(Discussion_Enligne.srv.addMessageRequest request) {
            return base.Channel.addMessage(request);
        }
        
        public void addMessage(string pseudo_em, string pseudo_recep, string text) {
            Discussion_Enligne.srv.addMessageRequest inValue = new Discussion_Enligne.srv.addMessageRequest();
            inValue.Body = new Discussion_Enligne.srv.addMessageRequestBody();
            inValue.Body.pseudo_em = pseudo_em;
            inValue.Body.pseudo_recep = pseudo_recep;
            inValue.Body.text = text;
            Discussion_Enligne.srv.addMessageResponse retVal = ((Discussion_Enligne.srv.ws_chatSoap)(this)).addMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Discussion_Enligne.srv.ws_chatSoap.BeginaddMessage(Discussion_Enligne.srv.addMessageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddMessage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginaddMessage(string pseudo_em, string pseudo_recep, string text, System.AsyncCallback callback, object asyncState) {
            Discussion_Enligne.srv.addMessageRequest inValue = new Discussion_Enligne.srv.addMessageRequest();
            inValue.Body = new Discussion_Enligne.srv.addMessageRequestBody();
            inValue.Body.pseudo_em = pseudo_em;
            inValue.Body.pseudo_recep = pseudo_recep;
            inValue.Body.text = text;
            return ((Discussion_Enligne.srv.ws_chatSoap)(this)).BeginaddMessage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion_Enligne.srv.addMessageResponse Discussion_Enligne.srv.ws_chatSoap.EndaddMessage(System.IAsyncResult result) {
            return base.Channel.EndaddMessage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndaddMessage(System.IAsyncResult result) {
            Discussion_Enligne.srv.addMessageResponse retVal = ((Discussion_Enligne.srv.ws_chatSoap)(this)).EndaddMessage(result);
        }
        
        private System.IAsyncResult OnBeginaddMessage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pseudo_em = ((string)(inValues[0]));
            string pseudo_recep = ((string)(inValues[1]));
            string text = ((string)(inValues[2]));
            return this.BeginaddMessage(pseudo_em, pseudo_recep, text, callback, asyncState);
        }
        
        private object[] OnEndaddMessage(System.IAsyncResult result) {
            this.EndaddMessage(result);
            return null;
        }
        
        private void OnaddMessageCompleted(object state) {
            if ((this.addMessageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addMessageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addMessageAsync(string pseudo_em, string pseudo_recep, string text) {
            this.addMessageAsync(pseudo_em, pseudo_recep, text, null);
        }
        
        public void addMessageAsync(string pseudo_em, string pseudo_recep, string text, object userState) {
            if ((this.onBeginaddMessageDelegate == null)) {
                this.onBeginaddMessageDelegate = new BeginOperationDelegate(this.OnBeginaddMessage);
            }
            if ((this.onEndaddMessageDelegate == null)) {
                this.onEndaddMessageDelegate = new EndOperationDelegate(this.OnEndaddMessage);
            }
            if ((this.onaddMessageCompletedDelegate == null)) {
                this.onaddMessageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddMessageCompleted);
            }
            base.InvokeAsync(this.onBeginaddMessageDelegate, new object[] {
                        pseudo_em,
                        pseudo_recep,
                        text}, this.onEndaddMessageDelegate, this.onaddMessageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion_Enligne.srv.getMessageResponse Discussion_Enligne.srv.ws_chatSoap.getMessage(Discussion_Enligne.srv.getMessageRequest request) {
            return base.Channel.getMessage(request);
        }
        
        public Discussion_Enligne.srv.returnList getMessage(string pseudo_recep) {
            Discussion_Enligne.srv.getMessageRequest inValue = new Discussion_Enligne.srv.getMessageRequest();
            inValue.Body = new Discussion_Enligne.srv.getMessageRequestBody();
            inValue.Body.pseudo_recep = pseudo_recep;
            Discussion_Enligne.srv.getMessageResponse retVal = ((Discussion_Enligne.srv.ws_chatSoap)(this)).getMessage(inValue);
            return retVal.Body.getMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Discussion_Enligne.srv.ws_chatSoap.BegingetMessage(Discussion_Enligne.srv.getMessageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetMessage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetMessage(string pseudo_recep, System.AsyncCallback callback, object asyncState) {
            Discussion_Enligne.srv.getMessageRequest inValue = new Discussion_Enligne.srv.getMessageRequest();
            inValue.Body = new Discussion_Enligne.srv.getMessageRequestBody();
            inValue.Body.pseudo_recep = pseudo_recep;
            return ((Discussion_Enligne.srv.ws_chatSoap)(this)).BegingetMessage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion_Enligne.srv.getMessageResponse Discussion_Enligne.srv.ws_chatSoap.EndgetMessage(System.IAsyncResult result) {
            return base.Channel.EndgetMessage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Discussion_Enligne.srv.returnList EndgetMessage(System.IAsyncResult result) {
            Discussion_Enligne.srv.getMessageResponse retVal = ((Discussion_Enligne.srv.ws_chatSoap)(this)).EndgetMessage(result);
            return retVal.Body.getMessageResult;
        }
        
        private System.IAsyncResult OnBegingetMessage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pseudo_recep = ((string)(inValues[0]));
            return this.BegingetMessage(pseudo_recep, callback, asyncState);
        }
        
        private object[] OnEndgetMessage(System.IAsyncResult result) {
            Discussion_Enligne.srv.returnList retVal = this.EndgetMessage(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetMessageCompleted(object state) {
            if ((this.getMessageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getMessageCompleted(this, new getMessageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getMessageAsync(string pseudo_recep) {
            this.getMessageAsync(pseudo_recep, null);
        }
        
        public void getMessageAsync(string pseudo_recep, object userState) {
            if ((this.onBegingetMessageDelegate == null)) {
                this.onBegingetMessageDelegate = new BeginOperationDelegate(this.OnBegingetMessage);
            }
            if ((this.onEndgetMessageDelegate == null)) {
                this.onEndgetMessageDelegate = new EndOperationDelegate(this.OnEndgetMessage);
            }
            if ((this.ongetMessageCompletedDelegate == null)) {
                this.ongetMessageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetMessageCompleted);
            }
            base.InvokeAsync(this.onBegingetMessageDelegate, new object[] {
                        pseudo_recep}, this.onEndgetMessageDelegate, this.ongetMessageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion_Enligne.srv.DeleteResponse Discussion_Enligne.srv.ws_chatSoap.Delete(Discussion_Enligne.srv.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public void Delete(string pseudo) {
            Discussion_Enligne.srv.DeleteRequest inValue = new Discussion_Enligne.srv.DeleteRequest();
            inValue.Body = new Discussion_Enligne.srv.DeleteRequestBody();
            inValue.Body.pseudo = pseudo;
            Discussion_Enligne.srv.DeleteResponse retVal = ((Discussion_Enligne.srv.ws_chatSoap)(this)).Delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Discussion_Enligne.srv.ws_chatSoap.BeginDelete(Discussion_Enligne.srv.DeleteRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDelete(string pseudo, System.AsyncCallback callback, object asyncState) {
            Discussion_Enligne.srv.DeleteRequest inValue = new Discussion_Enligne.srv.DeleteRequest();
            inValue.Body = new Discussion_Enligne.srv.DeleteRequestBody();
            inValue.Body.pseudo = pseudo;
            return ((Discussion_Enligne.srv.ws_chatSoap)(this)).BeginDelete(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion_Enligne.srv.DeleteResponse Discussion_Enligne.srv.ws_chatSoap.EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDelete(System.IAsyncResult result) {
            Discussion_Enligne.srv.DeleteResponse retVal = ((Discussion_Enligne.srv.ws_chatSoap)(this)).EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pseudo = ((string)(inValues[0]));
            return this.BeginDelete(pseudo, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            this.EndDelete(result);
            return null;
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(string pseudo) {
            this.DeleteAsync(pseudo, null);
        }
        
        public void DeleteAsync(string pseudo, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        pseudo}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion_Enligne.srv.GetParticipantsResponse Discussion_Enligne.srv.ws_chatSoap.GetParticipants(Discussion_Enligne.srv.GetParticipantsRequest request) {
            return base.Channel.GetParticipants(request);
        }
        
        public Discussion_Enligne.srv.ArrayOfString GetParticipants() {
            Discussion_Enligne.srv.GetParticipantsRequest inValue = new Discussion_Enligne.srv.GetParticipantsRequest();
            inValue.Body = new Discussion_Enligne.srv.GetParticipantsRequestBody();
            Discussion_Enligne.srv.GetParticipantsResponse retVal = ((Discussion_Enligne.srv.ws_chatSoap)(this)).GetParticipants(inValue);
            return retVal.Body.GetParticipantsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Discussion_Enligne.srv.ws_chatSoap.BeginGetParticipants(Discussion_Enligne.srv.GetParticipantsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetParticipants(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetParticipants(System.AsyncCallback callback, object asyncState) {
            Discussion_Enligne.srv.GetParticipantsRequest inValue = new Discussion_Enligne.srv.GetParticipantsRequest();
            inValue.Body = new Discussion_Enligne.srv.GetParticipantsRequestBody();
            return ((Discussion_Enligne.srv.ws_chatSoap)(this)).BeginGetParticipants(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion_Enligne.srv.GetParticipantsResponse Discussion_Enligne.srv.ws_chatSoap.EndGetParticipants(System.IAsyncResult result) {
            return base.Channel.EndGetParticipants(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Discussion_Enligne.srv.ArrayOfString EndGetParticipants(System.IAsyncResult result) {
            Discussion_Enligne.srv.GetParticipantsResponse retVal = ((Discussion_Enligne.srv.ws_chatSoap)(this)).EndGetParticipants(result);
            return retVal.Body.GetParticipantsResult;
        }
        
        private System.IAsyncResult OnBeginGetParticipants(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetParticipants(callback, asyncState);
        }
        
        private object[] OnEndGetParticipants(System.IAsyncResult result) {
            Discussion_Enligne.srv.ArrayOfString retVal = this.EndGetParticipants(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetParticipantsCompleted(object state) {
            if ((this.GetParticipantsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetParticipantsCompleted(this, new GetParticipantsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetParticipantsAsync() {
            this.GetParticipantsAsync(null);
        }
        
        public void GetParticipantsAsync(object userState) {
            if ((this.onBeginGetParticipantsDelegate == null)) {
                this.onBeginGetParticipantsDelegate = new BeginOperationDelegate(this.OnBeginGetParticipants);
            }
            if ((this.onEndGetParticipantsDelegate == null)) {
                this.onEndGetParticipantsDelegate = new EndOperationDelegate(this.OnEndGetParticipants);
            }
            if ((this.onGetParticipantsCompletedDelegate == null)) {
                this.onGetParticipantsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetParticipantsCompleted);
            }
            base.InvokeAsync(this.onBeginGetParticipantsDelegate, null, this.onEndGetParticipantsDelegate, this.onGetParticipantsCompletedDelegate, userState);
        }
    }
}
